source 'https://rubygems.org'

gem 'rails', '~> 4.2.5'
gem 'sqlite3'
gem 'hamlit'
gem 'devise'

gemspec path: '../../../admin4rails'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  gem 'bullet'
  gem 'spring'
  gem 'lograge'
end
